version: "3.5"
networks:
  default:
    name: qday-indexer
services:
  pg:
    container_name: indexer-db
    image: postgres:14.10
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/postgres/datadir:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=abe_user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=abe_indexer
    ports:
      - 5432:5432
  indexer:
    container_name: indexer-server
    image: ghcr.io/qday-io/qday-abel-bridge-indexer:0.2.2
    restart: always
    depends_on:
      - pg
    ports:
      - 9090:9090
      - 9091:9091
    volumes:
      - ./abi.json:/app/abi.json
      - ./.env:/app/.env
    command:
      - /app/abe-indexer
      - start