statedb:
  host: "190.92.213.101"
  port: 5432
  user: "state_user"
  password: "state_password"
  dbname: "state_db"
  sslmode: "disable"

committerdb:
  host: "190.92.213.101"
  port: 3366
  user: "root"
  password: "root"
  dbname: "abe_committer"
